### ISSUE TITLE
More checkpoints and zero shot comparison with clip

### ISSUE THREAD

**Issue by nikky4D** [ml-jku/cloob#1]
Hi,

Are there any more checkpoints? In the model_configs folder, I see several jsons but we can only download the RN50 and RN50x4 checkpoints.

Also, is it possible to add zero shot comparison with original clip models?

**Comment by fuersta** [comment]
Hi,

no, we only provide the RN50 model, which can be compared to the results of CLIP, and the RN50x4 model which is our biggest and best performing model.

What do you mean with zero shot comparison with original clip? OpenAI provides their models in their own repo, you could use these to check zero shot on the datasets we provide, like Birdsnap or Flowers.

**Comment by nikky4D** [comment]
Thanks for the response. For CLIP comparison, I will check their repo for their results. Thanks
