### ISSUE TITLE
Empty folders in preprocessed birdsnap testset

### ISSUE THREAD

**Issue by ChenDelong1999** [ml-jku/cloob#10]
subfolders 046, 066, 123, 299, 302, 351, 403, 436, 465 are empty.

**Comment by fuersta** [comment]
At the time of downloading this dataset, these images were not available unfortunately.
That is the reason why the test size of Birdsnap is only 1855, compared to the full 2443.
We state this also in the appendix of the paper.
You can find the resources to download the dataset here:
http://thomasberg.org/datasets/birdsnap/1.1/birdsnap.tgz
