### ISSUE TITLE
YFCC Download

### ISSUE THREAD

**Issue by kshama2705** [ml-jku/cloob#14]
Hi 

Could you provide more details on how to download the YFCC subset beyond the TSV file. I have checked some online resources but those solutions take upwards of 100 hours to just create the SQL table. It would be of great help if you could shed some light on your data download process.

**Comment by Ohtar10** [comment]
Hello!

TSV files contains the photo ids and paths to fetch both the images and the captions. The images reside in the mmc bucket, and the captions reside in the SQL table file.

You don't need to create an SQL file from scratch. There is one already for you in the [mmc bucket](https://multimedia-commons.s3-us-west-2.amazonaws.com/index.html?prefix=tools/etc/). This file can be read with simple sqlite3:

```sql
$ sqlite3
sqlite> .open yfcc100m_dataset.sql
sqlite> .tables
yfcc100m_dataset
sqlite> select * from yfcc100m_dataset limit 10;
```

You would need to join both the TSV and SQL file (by `photoid`), it can be done in the same sqlite session, it will take time, but certainly less than 100 hours and this is needed only once. You can export the join as a separate tsv or csv file.

Then you can use the product of the join to fetch the actual images from the bucket. Finally, you would need to format the data pairs using [webdataset](https://webdataset.github.io/webdataset/), so you can create shards of image-caption pairs for training data loading.

Hope it helps!
