### ISSUE TITLE
Existing Modern Hopfield Repository Not Used?

### ISSUE THREAD

**Issue by rohan-mehta-1024** [ml-jku/cloob#4]
Why is the existing code for the Modern Hopfield Net (which has its own Github repository) not used here? And if I wanted to use it instead, what arguments would I have to call it with to get the same result as here?

**Comment by fuersta** [comment]
The existing code for the model Hopfield networks is very general, therefore during the project we decided to use our own implementation. We now have exchanged our implementation with the existing `hopfield-layers`. You can see the arguments needed in the following lines of code:
https://github.com/ml-jku/cloob/blob/8a16009440f8e8eb9acba8fbb046180719003b28/src/training/train.py#L75-L90
