### ISSUE TITLE
What do the training acc/loss graphs look like?

### ISSUE THREAD

**Issue by rohan-mehta-1024** [ml-jku/cloob#9]
Hello,

 I am trying to train a similar architecture in a self-supervised way. However, for the pre-text task the loss plateaus relatively quickly. What are the various graphs that were generated when this architecture was trained, both for accuracy and loss? Thank you.

**Comment by fuersta** [comment]
Hello,

as we did a cosine decay with restarts, the loss goes down until the restart. Same for the accuracy, which steadily increases. We did not encounter a plateaus in the loss or accuracy.
